version: '3.8'

services:
  danahecrafts:
    image: ghcr.io/larissaguaman1/danahe-magical-crafts:1.0.0
    networks:
      - traefik-public
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"

        # HTTP
        - "traefik.http.routers.danahecrafts.rule=Host(`larissa.byronrm.com`)"
        - "traefik.http.routers.danahecrafts.entrypoints=http"
        - "traefik.http.routers.danahecrafts.middlewares=danahecrafts-https-redirect"

        # Redirección a HTTPS
        - "traefik.http.middlewares.danahecrafts-https-redirect.redirectscheme.scheme=https"

        # HTTPS
        - "traefik.http.routers.danahecrafts-secure.rule=Host(`larissa.byronrm.com`)"
        - "traefik.http.routers.danahecrafts-secure.entrypoints=https"
        - "traefik.http.routers.danahecrafts-secure.tls=true"
        - "traefik.http.routers.danahecrafts-secure.tls.certresolver=http"
        - "traefik.http.routers.danahecrafts-secure.service=danahecrafts"

        # Puerto interno de Flask
        - "traefik.http.services.danahecrafts.loadbalancer.server.port=5000"

        # Red de Traefik
        - "traefik.docker.network=traefik-public"

networks:
  traefik-public:
    external: true